### ISSUE TITLE
iframe error

### ISSUE THREAD

**Issue by ianhobbs** [ausi/respimagelint#26]
I get an error.

Error: Failed loading page into iframe.

Chrome 52

**Comment by ausi** [comment]
Do you use the `X-Frame-Options: deny` HTTP header?

The bookmarklet renders the page in several different viewports using an iframe. Because of that, it’s required that loading the page in an iframe is allowed. Setting the header to `X-Frame-Options: sameorigin` should be enough to make the bookmarklet work.

**Comment by urfusion** [comment]
That is my htaccess but still I am getting the same issue

    Header set Connection keep-alive
    Header set X-XSS-Protection "1; mode=block"
    Header set X-Frame-Options "sameorigin"
    Header set X-Content-Type-Options "nosniff"
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
    Header set Feature-Policy "geolocation 'self'; vibrate 'none'"
