### ISSUE TITLE
Detection of image width broken in slideshow

### ISSUE THREAD

**Issue by jordanade** [ausi/respimagelint#48]
Try linting this URL:
https://whalebeing.com/

The four images in the slideshow all fail with the suggestion that "100vw" is the wrong width, and the actual width is some smaller number, which changes each time I rerun the linter. But the images are indeed displayed at 100vw.

My slideshow library is slick-carousel—is that the source of the problem?

**Comment by ausi** [comment]
It looks like your slider script doesn’t instantaneously react to window resize events. Maybe it debounces the event or something similar.

Because of that the images are not displayed at 100vw directly after a window resize which the linter relies upon.

I think in this case you can safely ignore that error.
