### ISSUE TITLE
`h` descriptor should be invalid

### ISSUE THREAD

**Issue by zcorpan** [ausi/respimagelint#7]
https://github.com/ausi/respimagelint/blob/master/src/linter/descriptors/wrongSize.md

`h` descriptor is not valid yet per spec.

**Comment by ausi** [comment]
I thought they are allowed for authors because [browsers already parse them as *future-compat-h*](https://html.spec.whatwg.org/multipage/embedded-content.html#parse-a-srcset-attribute) and I saw some responsive images examples using them, although I didn’t find out a reasons why to use them.

Do you consider it bad practice to already use `h` descriptors (together with `w` descriptors) today?

**Comment by zcorpan** [comment]
They are not allowed to be used. The examples you saw are probably written against the *old* `srcset` spec, which had different semantics for `w` and `h` (they were for art direction; the current spec uses `<source media>` for that).

It's bad practice, yes; similar to using `<foobar>` -- it's reserved for future extensions in the language itself. If you use it, either your page breaks when the future extension comes into being, or you prevent that future extension from using the name `foobar` and a different name has to be minted.

**Comment by ausi** [comment]
Makes sense. Is fixed now.
