### ISSUE TITLE
The linter freezes on Jake’s blog post

### ISSUE THREAD

**Issue by simevidas** [ausi/respimagelint#8]
1. Go to https://jakearchibald.com/2015/anatomy-of-responsive-images/; that blog post contains inline demos of various forms of responsive images
2. Run the linter bookmarklet

I’ve tried in Firefox and Chrome, and the linter freezes at 22% and 99% respectively.

Could you try to reproduce this issue?

**Comment by ausi** [comment]
Thanks for reporting this bug.

I was able to reproduce this issue, the freezing on 22% seems to occur on HiDPI screens only, but at 99% it freezes always.

It looks like the issue is caused by the image [f1-focused-1406.jpg](https://jakearchibald.com/static/posts/responsive-images/f1-focused-1406.jpg) from:

```html
<source
	media="(max-width: 800px)"
	srcset="
		/static/posts/responsive-images/f1-focused-800.867f0b0b832f.jpg 800w,
		/static/posts/responsive-images/f1-focused-1406.jpg 1406w
	"
	sizes="(min-width: 530px) calc(100vw - 96px), 100vw"
>
```

The DevTools in both browsers show that the image loads very very long:

<img width="416" alt="dev-tools-chrome" src="https://cloud.githubusercontent.com/assets/367169/15275147/baf12b94-1ac3-11e6-9c4d-f6ee83445b16.png">

<img width="471" alt="dev-tools-firefox" src="https://cloud.githubusercontent.com/assets/367169/15275148/c705c2c8-1ac3-11e6-800b-6c8662720c91.png">

And Firefox reports an “Image corrupt or truncated.” error.

I think that there is a problem with that image itself or with delivery on the server side. Maybe @jakearchibald could take a look at this specific image: <https://jakearchibald.com/static/posts/responsive-images/f1-focused-1406.jpg>

**Comment by jakearchibald** [comment]
Fixed. My bad. Server was out of disk space. I am bad at sys-ops.

**Comment by ausi** [comment]
Thanks! The bookmarklet runs fine on your site now.

By the way, while testing the bookmarklet on your blog post I noticed a small bug in the F1-car image: IMO the media attribute of the first `<source>` should be `(max-width: 799px)` instead of `(max-width: 800px)`.

**Comment by jakearchibald** [comment]
This linter is great!
